app = "dotnet-travelers"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
    [http_service.concurrency]
      type = "connections"
      hard_limit = 5000
      soft_limit = 500

[checks]
  [checks.app_tcp_check]
    port = 8080
    type = "tcp"
    grace_period = "3s"
    interval = "15s"
    timeout = "10s"