app = "dotnet-travelers"
primary_region = "sin"

[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
#  auto_stop_machines = true

[services.concurrency]
hard_limit = 100
soft_limit = 75
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[checks]
[checks.alive]
type = "tcp"
interval = "15s"
timeout = "2s"
grace_period = "5s"
